sudo: required
services:
  - docker

# Build a test version
before_install:
  - docker build -t neeraj76/react-complex -f ./client/Dockerfile.dev ./client

# Primary test running section. If any script in this section exits with an error code
# then a build failure is assumed.
script:
  - docker run -e CI=true neeraj76/react-complex npm test

# If tests on test version are successful then we build a production version
after_success:
  - docker build -t neeraj76/multi-client ./client
  - docker build -t neeraj76/multi-nginx ./nginx
  - docker build -t neeraj76/multi-server ./server
  - docker build -t neeraj76/multi-worker ./worker

  # Login to docker CLI. Username, password are entered in Travis environment
  
  # Push above images to dockerhub