sudo: required
services:
  - docker

# Build a test version
before_install:
  - docker build -t neeraj76/react-multi -f ./client/Dockerfile.dev ./client

# Primary test running section. If any script in this section exits with an error code
# then a build failure is assumed.
script:
  - docker run -e CI=true neeraj76/react-multi npm test

# If tests on test version are successful then we build a production version
after_success:
  - docker build -t neeraj76/multi-client ./client
  - docker build -t neeraj76/multi-nginx ./nginx
  - docker build -t neeraj76/multi-server ./server
  - docker build -t neeraj76/multi-worker ./worker

  # Login to docker CLI. Username, password are entered in Travis environment
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push above images to dockerhub
  - docker push neeraj76/multi-client
  - docker push neeraj76/multi-nginx
  - docker push neeraj76/multi-server
  - docker push neeraj76/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-764022628003"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY